package middleware

import (
	"context"
	"net/http"
	"regexp"
	"strings"
)
type BotDetector struct {
}	})		next.ServeHTTP(w, r)		}			return			http.Error(w, "Bot detected", http.StatusForbidden)			// Return a challenge or block			r = r.WithContext(ctx)			ctx = context.WithValue(ctx, "bot_user_agent", r.UserAgent())			ctx = context.WithValue(ctx, "block_reason", "bot_detected")			ctx := context.WithValue(r.Context(), "blocked", true)		if bd.IsSuspicious(r) {	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {func (bd *BotDetector) Middleware(next http.Handler) http.Handler {}	return false	}		return true	if referer != "" && !strings.HasPrefix(referer, "http") {	referer := r.Header.Get("Referer")	// Check for suspicious header combinations	}		return true	if r.Header.Get("Accept-Language") == "" && bd.strictMode {	}		return true	if r.Header.Get("Accept") == "" {	// Check for missing common headers	}		return true	if bd.IsBot(userAgent) {	// Check user agent	userAgent := r.UserAgent()func (bd *BotDetector) IsSuspicious(r *http.Request) bool {}	return false	}		}			return true		if re.MatchString(userAgent) {	for _, re := range bd.suspiciousBots {	// Check for suspicious patterns	}		}			return false		if re.MatchString(userAgent) {	for _, re := range bd.whitelistedBots {	// Check if it's a whitelisted bot	}		return true // Empty user agent is suspicious	if userAgent == "" {func (bd *BotDetector) IsBot(userAgent string) bool {}	return regexps	}		}			regexps = append(regexps, re)		if err == nil {		re, err := regexp.Compile(pattern)	for _, pattern := range patterns {	regexps := make([]*regexp.Regexp, 0, len(patterns))func compileRegexps(patterns []string) []*regexp.Regexp {}	return bd	}		strictMode:      strictMode,		whitelistedBots: compileRegexps(knownBots),		suspiciousBots:  compileRegexps(suspiciousBots),		knownBots:       compileRegexps(knownBots),	bd := &BotDetector{	}		`(?i)headless`,		`(?i)selenium`,		`(?i)phantom`,		`(?i)scan`,		`(?i)http`,		`(?i)java`,		`(?i)python`,		`(?i)wget`,		`(?i)curl`,		`(?i)scraper`,		`(?i)spider`,		`(?i)crawler`,		`(?i)bot`,	suspiciousBots := []string{	// Suspicious patterns	}		`(?i)linkedinbot`,		`(?i)twitterbot`,		`(?i)facebookexternalhit`,		`(?i)yandexbot`,		`(?i)baiduspider`,		`(?i)duckduckbot`,		`(?i)slurp`, // Yahoo		`(?i)bingbot`,		`(?i)googlebot`,	knownBots := []string{	// Known legitimate botsfunc NewBotDetector(strictMode bool) *BotDetector {}	strictMode      bool	whitelistedBots []*regexp.Regexp	suspiciousBots  []*regexp.Regexp	knownBots       []*regexp.Regexp
